INSTRUCTION_SET = {
"NOP": {"Opcode": 0x00, "Bytes": 1 },
"LXI": {"Opcode": 0x01, "Bytes": 3 },
"STAX B":{"Opcode": 0x02, "Bytes": 1 },
"INX B": {"Opcode": 0x03, "Bytes": 1},
"INR B": {"Opcode": 0x04, "Bytes": 1},
"DCR B": {"Opcode": 0x05, "Bytes": 1},
"MVI B,": {"Opcode": 0x06, "Bytes": 2},
"RLC": {"Opcode": 0x07, "Bytes": 1},
"*NOP": {"Opcode": 0x08, "Bytes": 1},
"DAD B": {"Opcode": 0x09, "Bytes": 1},
"LDAX B": {"Opcode": 0x0A, "Bytes": 1},
"DCX B": {"Opcode": 0x0B, "Bytes": 1},
"INR C": {"Opcode": 0x0C, "Bytes": 1},
"DCR C": {"Opcode": 0x0D, "Bytes": 1},
"MVI C,": {"Opcode": 0x0E, "Bytes": 2},
"RRC": {"Opcode": 0x0F, "Bytes": 1},
    
"*NOP": {"Opcode": 0x10, "Bytes": 1},
"LXI D,": {"Opcode": 0x11, "Bytes": 3},
"STAX D": {"Opcode": 0x12, "Bytes": 1},
"INX D": {"Opcode": 0x13, "Bytes": 1},
"INR D": {"Opcode": 0x14, "Bytes": 1},
"DCR D": {"Opcode": 0x15, "Bytes": 1},
"MVI D,": {"Opcode": 0x16, "Bytes": 2},
"RAL": {"Opcode": 0x17, "Bytes": 1},
"*NOP": {"Opcode": 0x18, "Bytes": 1},
"DAD D": {"Opcode": 0x19, "Bytes": 1},
"LDAX D": {"Opcode": 0x1A, "Bytes": 1},
"DCX D": {"Opcode": 0x1B, "Bytes": 1},
"INR E": {"Opcode": 0x1C, "Bytes": 1},
"DCR E": {"Opcode": 0x1D, "Bytes": 1},
"MVI E,": {"Opcode": 0x1E, "Bytes": 2},
"RAR": {"Opcode": 0x1F, "Bytes": 1},
    
"*NOP": {"Opcode": 0x20, "Bytes": 1},
"LXI H,": {"Opcode": 0x21, "Bytes": 3},
"SHLD": {"Opcode": 0x22, "Bytes": 3},
"INX H": {"Opcode": 0x23, "Bytes": 1},
"INR H": {"Opcode": 0x24, "Bytes": 1},
"DCR H": {"Opcode": 0x25, "Bytes": 1},
"MVI H,": {"Opcode": 0x26, "Bytes": 2},
"DAA": {"Opcode": 0x27, "Bytes": 1},
"*NOP": {"Opcode": 0x28, "Bytes": 1},
"DAD H": {"Opcode": 0x29, "Bytes": 1},
"LHLD": {"Opcode": 0x2A, "Bytes": 3},
"DCX H": {"Opcode": 0x2B, "Bytes": 1},
"INR L": {"Opcode": 0x2C, "Bytes": 1},
"DCR L": {"Opcode": 0x2D, "Bytes": 1},
"MVI L,": {"Opcode": 0x2E, "Bytes": 2},
"CMA": {"Opcode": 0x2F, "Bytes": 1},
    
"*NOP": {"Opcode": 0x30, "Bytes": 1},
"LXI SP,": {"Opcode": 0x31, "Bytes": 3},
"STA": {"Opcode": 0x32, "Bytes": 3},
"INX SP": {"Opcode": 0x33, "Bytes": 1},
"INR M": {"Opcode": 0x34, "Bytes": 1},
"DCR M": {"Opcode": 0x35, "Bytes": 1},
"MVI M,": {"Opcode": 0x36, "Bytes": 2},
"STC": {"Opcode": 0x37, "Bytes": 1},
"*NOP": {"Opcode": 0x38, "Bytes": 1},
"DAD SP": {"Opcode": 0x39, "Bytes": 1},
"LDA": {"Opcode": 0x3A, "Bytes": 3},
"DCX SP": {"Opcode": 0x3B, "Bytes": 1},
"INR A": {"Opcode": 0x3C, "Bytes": 1},
"DCR A": {"Opcode": 0x3D, "Bytes": 1},
"MVI A,": {"Opcode": 0x3E, "Bytes": 2},
"CMC": {"Opcode": 0x3F, "Bytes": 1},
    
"MOV B,B": {"Opcode": 0x40, "Bytes": 1},
"MOV B,C": {"Opcode": 0x41, "Bytes": 1},
"MOV B,D": {"Opcode": 0x42, "Bytes": 1},
"MOV B,E": {"Opcode": 0x43, "Bytes": 1},
"MOV B,H": {"Opcode": 0x44, "Bytes": 1},
"MOV B,L": {"Opcode": 0x45, "Bytes": 1},
"MOV B,M": {"Opcode": 0x46, "Bytes": 1},
"MOV B,A": {"Opcode": 0x47, "Bytes": 1},
"MOV C,B": {"Opcode": 0x48, "Bytes": 1},
"MOV C,C": {"Opcode": 0x49, "Bytes": 1},
"MOV C,D": {"Opcode": 0x4A, "Bytes": 1},
"MOV C,E": {"Opcode": 0x4B, "Bytes": 1},
"MOV C,H": {"Opcode": 0x4C, "Bytes": 1},
"MOV C,L": {"Opcode": 0x4D, "Bytes": 1},
"MOV C,M": {"Opcode": 0x4E, "Bytes": 1},
"MOV C,A": {"Opcode": 0x4F, "Bytes": 1},
    
"MOV D,B": {"Opcode": 0x50, "Bytes": 1},
"MOV D,C": {"Opcode": 0x51, "Bytes": 1},
"MOV D,D": {"Opcode": 0x52, "Bytes": 1},
"MOV D,E": {"Opcode": 0x53, "Bytes": 1},
"MOV D,H": {"Opcode": 0x54, "Bytes": 1},
"MOV D,L": {"Opcode": 0x55, "Bytes": 1},
"MOV D,M": {"Opcode": 0x56, "Bytes": 1},
"MOV D,A": {"Opcode": 0x57, "Bytes": 1},
"MOV E,B": {"Opcode": 0x58, "Bytes": 1},
"MOV E,C": {"Opcode": 0x59, "Bytes": 1},
"MOV E,D": {"Opcode": 0x5A, "Bytes": 1},
"MOV E,E": {"Opcode": 0x5B, "Bytes": 1},
"MOV E,H": {"Opcode": 0x5C, "Bytes": 1},
"MOV E,L": {"Opcode": 0x5D, "Bytes": 1},
"MOV E,M": {"Opcode": 0x5E, "Bytes": 1},
"MOV E,A": {"Opcode": 0x5F, "Bytes": 1},
    
"MOV H,B": {"Opcode": 0x60, "Bytes": 1},
"MOV H,C": {"Opcode": 0x61, "Bytes": 1},
"MOV H,D": {"Opcode": 0x62, "Bytes": 1},
"MOV H,E": {"Opcode": 0x63, "Bytes": 1},
"MOV H,H": {"Opcode": 0x64, "Bytes": 1},
"MOV H,L": {"Opcode": 0x65, "Bytes": 1},
"MOV H,M": {"Opcode": 0x66, "Bytes": 1},
"MOV H,A": {"Opcode": 0x67, "Bytes": 1},
"MOV L,B": {"Opcode": 0x68, "Bytes": 1},
"MOV L,C": {"Opcode": 0x69, "Bytes": 1},
"MOV L,D": {"Opcode": 0x6A, "Bytes": 1},
"MOV L,E": {"Opcode": 0x6B, "Bytes": 1},
"MOV L,H": {"Opcode": 0x6C, "Bytes": 1},
"MOV L,L": {"Opcode": 0x6D, "Bytes": 1},
"MOV L,M": {"Opcode": 0x6E, "Bytes": 1},
"MOV L,A": {"Opcode": 0x6F, "Bytes": 1},
    
"MOV M,B": {"Opcode": 0x70, "Bytes": 1},
"MOV M,C": {"Opcode": 0x71, "Bytes": 1},
"MOV M,D": {"Opcode": 0x72, "Bytes": 1},
"MOV M,E": {"Opcode": 0x73, "Bytes": 1},
"MOV M,H": {"Opcode": 0x74, "Bytes": 1},
"MOV M,L": {"Opcode": 0x75, "Bytes": 1},
"HLT": {"Opcode": 0x76, "Bytes": 1},
"MOV M,A": {"Opcode": 0x77, "Bytes": 1},
"MOV A,B": {"Opcode": 0x78, "Bytes": 1},
"MOV A,C": {"Opcode": 0x79, "Bytes": 1},
"MOV A,D": {"Opcode": 0x7A, "Bytes": 1},
"MOV A,E": {"Opcode": 0x7B, "Bytes": 1},
"MOV A,H": {"Opcode": 0x7C, "Bytes": 1},
"MOV A,L": {"Opcode": 0x7D, "Bytes": 1},
"MOV A,M": {"Opcode": 0x7E, "Bytes": 1},
"MOV A,A": {"Opcode": 0x7F, "Bytes": 1},
    
"ADD B": {"Opcode": 0x80, "Bytes": 1},
"ADD C": {"Opcode": 0x81, "Bytes": 1},
"ADD D": {"Opcode": 0x82, "Bytes": 1},
"ADD E": {"Opcode": 0x83, "Bytes": 1},
"ADD H": {"Opcode": 0x84, "Bytes": 1},
"ADD L": {"Opcode": 0x85, "Bytes": 1},
"ADD M": {"Opcode": 0x86, "Bytes": 1},
"ADD A": {"Opcode": 0x87, "Bytes": 1},
"ADC B": {"Opcode": 0x88, "Bytes": 1},
"ADC C": {"Opcode": 0x89, "Bytes": 1},
"ADC D": {"Opcode": 0x8A, "Bytes": 1},
"ADC E": {"Opcode": 0x8B, "Bytes": 1},
"ADC H": {"Opcode": 0x8C, "Bytes": 1},
"ADC L": {"Opcode": 0x8D, "Bytes": 1},
"ADC M": {"Opcode": 0x8E, "Bytes": 1},
"ADC A": {"Opcode": 0x8F, "Bytes": 1},
    
"SUB B": {"Opcode": 0x90, "Bytes": 1},
"SUB C": {"Opcode": 0x91, "Bytes": 1},
"SUB D": {"Opcode": 0x92, "Bytes": 1},
"SUB E": {"Opcode": 0x93, "Bytes": 1},
"SUB H": {"Opcode": 0x94, "Bytes": 1},
"SUB L": {"Opcode": 0x95, "Bytes": 1},
"SUB M": {"Opcode": 0x96, "Bytes": 1},
"SUB A": {"Opcode": 0x97, "Bytes": 1},
"SBB B": {"Opcode": 0x98, "Bytes": 1},
"SBB C": {"Opcode": 0x99, "Bytes": 1},
"SBB D": {"Opcode": 0x9A, "Bytes": 1},
"SBB E": {"Opcode": 0x9B, "Bytes": 1},
"SBB H": {"Opcode": 0x9C, "Bytes": 1},
"SBB L": {"Opcode": 0x9D, "Bytes": 1},
"SBB M": {"Opcode": 0x9E, "Bytes": 1},
"SBB A": {"Opcode": 0x9F, "Bytes": 1},
    
"ANA B": {"Opcode": 0xA0, "Bytes": 1},
"ANA C": {"Opcode": 0xA1, "Bytes": 1},
"ANA D": {"Opcode": 0xA2, "Bytes": 1},
"ANA E": {"Opcode": 0xA3, "Bytes": 1},
"ANA H": {"Opcode": 0xA4, "Bytes": 1},
"ANA L": {"Opcode": 0xA5, "Bytes": 1},
"ANA M": {"Opcode": 0xA6, "Bytes": 1},
"ANA A": {"Opcode": 0xA7, "Bytes": 1},
"XRA B": {"Opcode": 0xA8, "Bytes": 1},
"XRA C": {"Opcode": 0xA9, "Bytes": 1},
"XRA D": {"Opcode": 0xAA, "Bytes": 1},
"XRA E": {"Opcode": 0xAB, "Bytes": 1},
"XRA H": {"Opcode": 0xAC, "Bytes": 1},
"XRA L": {"Opcode": 0xAD, "Bytes": 1},
"XRA M": {"Opcode": 0xAE, "Bytes": 1},
"XRA A": {"Opcode": 0xAF, "Bytes": 1},
    
"ORA B": {"Opcode": 0xB0, "Bytes": 1},
"ORA C": {"Opcode": 0xB1, "Bytes": 1},
"ORA D": {"Opcode": 0xB2, "Bytes": 1},
"ORA E": {"Opcode": 0xB3, "Bytes": 1},
"ORA H": {"Opcode": 0xB4, "Bytes": 1},
"ORA L": {"Opcode": 0xB5, "Bytes": 1},
"ORA M": {"Opcode": 0xB6, "Bytes": 1},
"ORA A": {"Opcode": 0xB7, "Bytes": 1},
"CMP B": {"Opcode": 0xB8, "Bytes": 1},
"CMP C": {"Opcode": 0xB9, "Bytes": 1},
"CMP D": {"Opcode": 0xBA, "Bytes": 1},
"CMP E": {"Opcode": 0xBB, "Bytes": 1},
"CMP H": {"Opcode": 0xBC, "Bytes": 1},
"CMP L": {"Opcode": 0xBD, "Bytes": 1},
"CMP M": {"Opcode": 0xBE, "Bytes": 1},
"CMP A": {"Opcode": 0xBF, "Bytes": 1},
    
"RNZ": {"Opcode": 0xC0, "Bytes": 1},
"POP B": {"Opcode": 0xC1, "Bytes": 1},
"JNZ": {"Opcode": 0xC2, "Bytes": 3},
"JMP": {"Opcode": 0xC3, "Bytes": 3},
"CNZ": {"Opcode": 0xC4, "Bytes": 3},
"PUSH B": {"Opcode": 0xC5, "Bytes": 1},
"ADI": {"Opcode": 0xC6, "Bytes": 2},
"RST 0": {"Opcode": 0xC7, "Bytes": 1},
"RZ": {"Opcode": 0xC8, "Bytes": 1},
"RET": {"Opcode": 0xC9, "Bytes": 1},
"JZ": {"Opcode": 0xCA, "Bytes": 3},
"*JMP": {"Opcode": 0xCB, "Bytes": 3},
"CZ": {"Opcode": 0xCC, "Bytes": 3},
"CALL": {"Opcode": 0xCD, "Bytes": 3},
"ACI": {"Opcode": 0xCE, "Bytes": 2},
"RST 1": {"Opcode": 0xCF, "Bytes": 1},
    
"RNC": {"Opcode": 0xD0, "Bytes": 1},
"POP D": {"Opcode": 0xD1, "Bytes": 1},
"JNC": {"Opcode": 0xD2, "Bytes": 3},
"OUT": {"Opcode": 0xD3, "Bytes": 2},
"CNC": {"Opcode": 0xD4, "Bytes": 3},
"PUSH D": {"Opcode": 0xD5, "Bytes": 1},
"SUI": {"Opcode": 0xD6, "Bytes": 2},
"RST 2": {"Opcode": 0xD7, "Bytes": 1},
"RC": {"Opcode": 0xD8, "Bytes": 1},
"*RET": {"Opcode": 0xD9,  "Bytes": 1},
"JC": {"Opcode": 0xDA,  "Bytes": 3},
"IN": {"Opcode": 0xDB, "Bytes": 2},
"CC": {"Opcode": 0xDC,  "Bytes": 3},
"*CALL": {"Opcode": 0xDD,  "Bytes": 3},
"SBI": {"Opcode": 0xDE, "Bytes": 3},
"RST 3": {"Opcode": 0xDF, "Bytes": 1},

"RPO": {"Opcode": 0xE0, "Bytes": 1},
"POP H" : {"Opcode": 0xE1, "Bytes": 1},
"JPO"   : {"Opcode": 0xE2, "Bytes": 3},
"XTHL"  : {"Opcode": 0xE3, "Bytes": 1},
"CPO"   : {"Opcode": 0xE4, "Bytes": 3},
"PUSH H": {"Opcode": 0xE5, "Bytes": 1},
"ANI"   : {"Opcode": 0xE6, "Bytes": 2},
"RST 4" : {"Opcode": 0xE7, "Bytes": 1},
"RPE"   : {"Opcode": 0xE8, "Bytes": 1},
"PCHL"  : {"Opcode": 0xE9, "Bytes": 1},
"JPE"   : {"Opcode": 0xEA, "Bytes": 3},
"XCHG"  : {"Opcode": 0xEB, "Bytes": 1},
"CPE"   : {"Opcode": 0xEC, "Bytes": 3},
"*CALL" : {"Opcode": 0xED, "Bytes": 3},
"XRI"   : {"Opcode": 0xEE, "Bytes": 2},
"RST 5" : {"Opcode": 0xEF, "Bytes": 1},

"RP": {"Opcode": 0xF0 , "Bytes": 1},
"POP PSW": {"Opcode": 0xF1, "Bytes": 1},
"JP": {"Opcode": 0xF2, "Bytes": 3},
"DI": {"Opcode": 0xF3, "Bytes": 1},
"CP": {"Opcode": 0xF4, "Bytes": 3},
"PUSH PSW": {"Opcode": 0xF5, "Bytes": 1},
"ORI": {"Opcode": 0xF6, "Bytes": 2},
"RST 6": {"Opcode": 0xF7, "Bytes": 1},
"RM": {"Opcode": 0xF8, "Bytes": 1},
"SPHL": {"Opcode": 0xF9, "Bytes": 1},
"JM": {"Opcode": 0xFA, "Bytes": 3},
"EI": {"Opcode": 0xFB, "Bytes": 1},
"CM": {"Opcode": 0xFC, "Bytes": 3},
"*CALL": {"Opcode": 0xFD, "Bytes": 3},
 "CPI": {"Opcode": 0xFE, "Bytes": 2},
"RST 7": {"Opcode": 0xFF, "Bytes": 1},
}