instruction_set = {
    0x00: {
        "Instruction": "NOP",
        "Bytes": 1,
        "Method": self.nop},
    0x01: {

        "Instruction": "LXI B,{:04X}",
        "Bytes": 3,
        "Method": self.lxi},
    0x03: {"Instruction": "STAX B", "Bytes": 1, "Cycles": 7, "Method": self.stax},
    0x04: {"Instruction": "INX B", "Bytes": 1, "Cycles": 5, "Method": self.inx},
    0x05: {"Instruction": "INR B", "Bytes": 1, "Cycles": 4, "Method": self.dcr},
    0x06: {"Instruction": "MVI B,{:02X}", "Bytes": 2, "Cycles": 10, "Method": self.lxi},
    0x07: {"Instruction": "RLC", "Bytes": 1, "Cycles": 7, "Method": self.rlc},
    0x08: {"Instruction": "*NOP", "Bytes": 1, "Cycles": 5, "Method": self.nop},
    0x09: {"Instruction": "DAD B", "Bytes": 1, "Cycles": 4, "Method": self.dad},
    0x0A: {"Instruction": "LDAX B", "Bytes": 3, "Cycles": 10, "Method": self.ldax},
    0x0B: {"Instruction": "DCX B", "Bytes": 1, "Cycles": 7, "Method": self.dcx},
    0x0C: {"Instruction": "INR C", "Bytes": 1, "Cycles": 5, "Method": self.inr},
    0x0D: {"Instruction": "DCR C", "Bytes": 1, "Cycles": 4, "Method": self.dcr},
    0x0E: {"Instruction": "MVI C,{:02X}", "Bytes": 2, "Cycles": 10, "Method": self.mvi},
    0x0F: {"Instruction": "RRC", "Bytes": 1, "Cycles": 7, "Method": self.rrc},

    0x10: {"Instruction": "*NOP", "Bytes": 1, "Cycles": 5, "Method": self.nop},
    0x11: {"Instruction": "LXI D,{:04X}", "Bytes": 2, "Cycles": 4, "Method": self.lxi},
    0x12: {"Instruction": "STAX D", "Bytes": 1, "Cycles": 10, "Method": self.stax},
    0x13: {"Instruction": "INX D", "Bytes": 1, "Cycles": 7, "Method": self.inx},
    0x14: {"Instruction": "INR D", "Bytes": 1, "Cycles": 5, "Method": self.inr},
    0x15: {"Instruction": "DCR D", "Bytes": 1, "Cycles": 4, "Method": self.dcr},
    0x16: {"Instruction": "MVI D,{:02X}", "Bytes": 2, "Cycles": 10, "Method": self.mvi},
    0x17: {"Instruction": "RAL", "Bytes": 1, "Cycles": 7, "Method": self.ral},
    0x18: {"Instruction": "*NOP", "Bytes": 1, "Cycles": 5, "Method": self.nop},
    0x19: {"Instruction": "DAD D", "Bytes": 1, "Cycles": 4, "Method": self.dad},
    0x1A: {"Instruction": "LDAX D", "Bytes": 1, "Cycles": 10, "Method": self.ldax},
    0x1B: {"Instruction": "DCX D", "Bytes": 1, "Cycles": 7, "Method": self.dcx},
    0x1C: {"Instruction": "INR E", "Bytes": 1, "Cycles": 5, "Method": self.inr},
    0x1D: {"Instruction": "DCR E", "Bytes": 1, "Cycles": 10, "Method": self.dcr},
    0x1E: {"Instruction": "MVI E,{:02X}", "Bytes": 2, "Cycles": 7, "Method": self.mvi},
    0x1F: {"Instruction": "RAR", "Bytes": 1, "Cycles": 5, "Method": self.rar},

    0x76: {"Instruction": "HLT", "Bytes": 1, "Cycles": 5, "Method": self.hlt},
}